stages:
  - build
  - test

b:docker:
  stage: build
  tags:
    - shell
  script:
    - docker build --pull -t boileaum/phypso:latest  -f ./docker/Dockerfile-user .

t:docker:burgers:
  stage: test
  tags:
    - shell
  script:
    - docker run boileaum/phypso /bin/bash -c 'cd phypso/burgers && pytest'

t:docker:stvenant:
  stage: test
  tags:
    - shell
  script:
    - docker run boileaum/phypso /bin/bash -c 'cd phypso/stvenant && pytest'

