stages:
  - build
  - test

b:docker:
  stage: build
  script:
    - docker build --pull -t boileaum/phypso:latest  -f ./docker/Dockerfile-user .

t:docker:burgers:
  stage: test
  script:
    - docker run boileaum/phypso /bin/bash -c 'cd burgers && pytest -v'

t:docker:stvenant:
  stage: test
  script:
    - docker run boileaum/phypso /bin/bash -c 'cd stvenant && pytest -v'

