version: '2'

services:
  deps:
    build:
      context: ..
      dockerfile: docker/Dockerfile-deps
    image: boileaum/phypso:deps

  env:
    build:
      context: .
      dockerfile: Dockerfile-env
    image: boileaum/phypso:env
    depends_on:
      - deps

  user:
    build:
      context: ../
      dockerfile: docker/Dockerfile-user
    image: boileaum/phypso:latest
    depends_on:
      - env

