FROM boileaum/phypso:env
MAINTAINER Matthieu Boileau <matthieu.boileau@math.unistra.fr>

COPY . $HOME/phypso
USER root
RUN chown -R euler:euler /home/euler
USER euler
WORKDIR $HOME/phypso

RUN make clean && make

CMD /bin/bash

