FROM ubuntu:latest

MAINTAINER Matthieu Boileau <matthieu.boileau@math.unistra.fr>

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN apt-get update --fix-missing && \
    apt-get install -y \ 
    sudo \
    vim \
    git \
    gfortran \
    python3-pip \
    python3-tk

RUN apt-get clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip3 install --upgrade pip && \
    pip3 install numpy && \
    pip3 install colorlog && \
    pip3 install scipy && \
    pip3 install matplotlib && \
    pip3 install numba && \
    pip3 install pythran && \
    pip3 install pandas && \
    pip3 install pytest && \
    pip3 install Cython && \
    rm -rf ~/.cache/pip/

CMD /bin/bash
