FROM boileaum/phypso:deps
MAINTAINER Matthieu Boileau <matthieu.boileau@math.unistra.fr>

RUN apt-get update --fix-missing && \
      apt-get install -y \
      vim

RUN apt-get clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN useradd -m -s /bin/bash  euler

CMD /bin/bash

